### ISSUE TITLE
IndexError: list out of range when converting alleles.loci/ipyrad file

### ISSUE THREAD

**Issue by kevinmneal** [edgardomortiz/fineRADstructure-tools#1]
Hi,

I'm trying to convert the alleles.loci file from ipyrad 0.7.22 [edit: it's actually 0.7.23], and running finerad_input.py I get this error:

``Traceback (most recent call last):
  File "../fineRADstructure-tools/finerad_input.py", line 181, in <module>
    main()
  File "../fineRADstructure-tools/finerad_input.py", line 174, in main
    pyrad_to_finerad(filename, outfile, minsample)
  File "../fineRADstructure-tools/finerad_input.py", line 67, in pyrad_to_finerad
    sample = line.split()[0].strip(">")[:-2] # Sample name does not include last two characters
IndexError: list index out of range
``

Any ideas for a fix? Thanks

**Comment by edgardomortiz** [comment]
I see, perhaps something changed with the latest version of ipyrad, could you send me the first 10000 lines of your alleles.loci?

**Comment by kevinmneal** [comment]
Command: python2 finerad_input.py -i nativesocal_min281.alleles.loci -t ipyrad

File is here (it's about 254 MB, unfortunately): [edited]

**Comment by kevinmneal** [comment]
Just saw your edit, here is the file for the first 10000 lines:

[edited]

**Comment by edgardomortiz** [comment]
Thanks for reporting the bug, it is fixed now.

Edgardo
