### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by tommydevitt** [edgardomortiz/fineRADstructure-tools#2]
Hi Edgardo,

Getting a syntax error when trying to use your script:

tom$ python finerad_input.py --input sosorum-min5.alleles.loci
  File "/finerad_input.py", line 57
    print str(locus_num)+" loci for "+str(len(genotypes))+" samples written to "+outfile
            ^
SyntaxError: invalid syntax

Thanks,
Tom

**Comment by edgardomortiz** [comment]
Hi Tom,
Unfortunately I haven't updated all my scripts to comply with python3 (which I guess you are using). I just did, please re-clone and try again. Alternatively, try the command without `python` in which case it will look for a python2 installed in your system.

Let me know if it works.


Edgardo

**Comment by tommydevitt** [comment]
Hi Edgardo,

It worked. Thanks for your prompt attention, and for a very useful script!

Best,
Tom

**Comment by edgardomortiz** [comment]
excellent, glad to hear it
