### ISSUE TITLE
Issue when converting alleles file from reference genome assembly

### ISSUE THREAD

**Issue by rilquer-mascarenhas** [edgardomortiz/fineRADstructure-tools#3]
Hi all. I am having trouble converting one of the output files in ipyrad to the finerad format. The alleles file for iPyrad v.0.9 is slightly different then previous version when using a reference genome, and I keep running into the following error when using the finerad_input.py script:

Traceback (most recent call last):
  File "./fineRADstructure-tools/finerad_input.py", line 183, in <module>
    main()
  File "./fineRADstructure-tools/finerad_input.py", line 176, in main
    pyrad_to_finerad(filename, outfile, minsample)
  File "./fineRADstructure-tools/finerad_input.py", line 101, in pyrad_to_finerad
    snp += allele[pos]
IndexError: string index out of range

I noticed with a few changes that changing the way that the loci are identified helped a little. In this version, with reference genome, by the end of each loci you have an identifier like |0:Contig name:Position of locus in the contig|, instead of the simpler |0| with denovo assemblies. I think these colons are messing up the script a little bit, so I dropped all this extra info in the identifiers using sed, but the script still doesn't work. Funny thing is that if I subset my alleles file for the first locus only, it works, but when I try to use the script for the complete alleles file, it doesn't. Does anyone know how to address this issue?

Thank you.

**Comment by edgardomortiz** [comment]
Interesting, could you email me a few loci from your alleles file? (not the one modified by `sed`, but the original). Last thing I remember, the lines that contain the info about informative sites `*` and uninformative sites `-` is messed up in the latest versions of ipyrad. Check the issue I submitted to ipyrad's GitHub page (I guess is not only a cosmetic issue):
https://github.com/dereneaton/ipyrad/issues/387

Edgardo

**Comment by rilquer-mascarenhas** [comment]
I'm sending below a subset of 9 loci from the original alleles file.

[bananaquit_ref_min10kb_subset.alleles.zip](https://github.com/edgardomortiz/fineRADstructure-tools/files/4377693/bananaquit_ref_min10kb_subset.alleles.zip)

Interestingly, when I used your script with this reduced file, after modifying it with sed, it worked fine (I didn't even have to use the -t flag to explicitly tell which file type it is, which I was using before to make it work on this new version outfiles).

**Comment by edgardomortiz** [comment]
OK, it seems that you have the formatting issue mentioned in dereneaton/ipyrad#387
You can wait for the new version of ipyrad or you can fix your `.alleles` file with sed:
```
sed -i 's|\/\/\ \ |\/\|g' file.alleles
```
and the try again with my script, please let me know if this fixes it or if a different issue arises

Edgardo

**Comment by rilquer-mascarenhas** [comment]
Thank you, I just tried it. Turns out using both your sed command and the one I was using solved the case. When I used just yours (but left my identified in that |0:Contig:Positions| format), the error persisted. But then I used my sed command:

`sed -i "s/:[a-zA-Z0-9]*_[a-zA-Z0-9]*:[a-zA-Z0-9]*-[a-zA-Z0-9]*//g" files.alleles`

after your sed command, and it worked.

Also, your command is missing a final bar right-towards slash before "|g". The command I used was:

`sed -i 's|\/\/\ \ |\/\/|g' file.alleles`

Anyway, thank you very much for responding so quickly!

**Comment by edgardomortiz** [comment]
You are right, I missed a slash, the correct way to fix the .alleles file from a reference analysis at this point is:
```
sed -i 's|\/\/\ \ |\/\/|g' file.alleles
```
I also updated the script so your `sed` command is not needed, the problem is that because the locus name now includes the `-` character for the coordinates it is taken as one of the SNPs, the fix should skip the locus names entirely. If you can, please reclone the repository and try the new version excluding your `sed` command.

Glad to help

Edgardo

**Comment by rilquer-mascarenhas** [comment]
I just tried it without my sed command and it worked.

Thank you.

**Comment by edgardomortiz** [comment]
excellent!
